---
- name: Get the undercloud base image
  get_url:
    url: '{{ undercloud_base_image_url }}'
    dest: '{{ working_dir }}/undercloud-base.qcow2'
    force: '{{ undercloud_overwrite_existing }}'

- name: Resize undercloud image (create target image)
  command: >
    qemu-img create -f qcow2 -o preallocation=off
    '{{ working_dir }}/undercloud-resized.qcow2'
    '{{ undercloud_disk_size }}G'

- name: Resize undercloud image (call virt-resize)
  command: >
    virt-resize --expand /dev/sda1
    '{{ working_dir }}/undercloud-base.qcow2'
    '{{ working_dir }}/undercloud-resized.qcow2'
  environment:
    LIBGUESTFS_BACKEND: direct

- name: Resize undercloud image (rename resized image)
  command: >
    mv -f {{ working_dir }}/undercloud-resized.qcow2
    {{ working_dir }}/undercloud-base.qcow2

- name: Template script to convert overcloud image to undercloud
  template:
    src: "{{ undercloud_convert_script }}"
    dest: "{{ working_dir }}/undercloud-convert.sh"

# LKS: do we really care about smp settings here?
- name: Convert the overcloud image to an undercloud image
  shell: >
    virt-customize -m {{ virt_customize_ram }}
    --smp {{ virt_customize_cpu }}
    -a {{ working_dir }}/undercloud-base.qcow2
    --run {{ working_dir }}/undercloud-convert.sh
  environment:
    LIBGUESTFS_BACKEND: direct
