---
# workarounds to not include a bunch of DIB elements with a single line of bash
# TODO: presently they are applied to overcloud-base.qcow, however ultimately should
# TODO: be migrated to a per-image setting (vs. assuming that file name, etc).
- name: Template script with workarounds for overcloud-full image
  template:
    src: "{{ artib_dib_workaround_script }}"
    dest: "{{ artib_working_dir }}/dib-workaround.sh"

- name: DIB workarounds
  shell: >
    virt-customize -m {{ artib_virt_customize_ram }}
    --smp {{ artib_virt_customize_cpu }}
    -a {{ artib_working_dir }}/overcloud-base.qcow2
    --run {{ artib_working_dir }}/dib-workaround.sh
  environment:
    LIBGUESTFS_BACKEND: direct
  when: artib_dib_workarounds

- name: script to prepare for image building with DIB
  template:
    src: "{{ artib_dib_prepare_script }}"
    dest: "{{ artib_working_dir }}/dib-prepare-script.sh"
    mode: 0744

- name: Run DIB prep script
  shell: >
    {{ artib_working_dir }}/dib-prepare-script.sh
  become: true

- name: ensure we can sudo without requiring tty for async tasks
  lineinfile:
    dest: /etc/sudoers
    line: '#Defaults requiretty'
    regexp: '^Defaults\s+requiretty'
    backup: yes
  become: true

# handle additional var env based DIB settings
- name: Optional DIB environment inject template
  template:
    src: dib-optional-env-inject.sh.j2
    dest: "{{ artib_working_dir }}/dib-optional-env-inject.sh"
    mode: 0744
  become: true

- name: Build the images using disk-image-create (in parallel).
  shell: |
    set -x
    export -p
    source {{ artib_working_dir }}/dib-optional-env-inject.sh
    export -p
    disk-image-create -a amd64 -o {{ artib_working_dir }}/{{ item.value.output_image }} \
    {% if item.value.elements is defined %}
    {{ item.value.elements | join(' ') }} \
    {% endif %}
    {% if item.value.projects is defined %}
    -p {{ item.value.projects | join(' -p ') }} \
    {% endif %}
    --min-tmpfs {{ item.value.min_tmpfs_size }} 2>&1 | tee {{ working_dir }}/{{ item.value.logfile }}
  environment:
    DIB_LOCAL_IMAGE: "{{ artib_working_dir }}/{{ item.value.base_image }}"
    ELEMENTS_PATH: "{{ item.value.elements_path | join(':') }}"
    DIB_DEFAULT_INSTALLTYPE: package
    {{ item.value.env }}
  async: 3600
  poll: 0
  register: "async_var_{{ item.key }}"
  with_dict: "{{ artib_dib_images }}"

- name: Async_Poll --> Wait for tasks to complete.
  async_status:
    jid: "async_var_{{ item.key }}.ansible_job_id"
  register: job_result
  until: job_result.finished
  retries: 720
  delay: 5
  with_dict: "{{ artib_dib_images }}"
