---
# workarounds to not include a bunch of DIB elements with a single line of bash
- name: Template script with workarounds for overcloud-full image
  template:
    src: "{{ artib_dib_workaround_script }}"
    dest: "{{ artib_working_dir }}/dib-workaround.sh"

- name: DIB workarounds
  shell: >
    virt-customize -v -m {{ artib_virt_customize_ram }}
    --smp {{ artib_virt_customize_cpu }}
    -a {{ artib_working_dir }}/overcloud-base.qcow2
    --run {{ artib_working_dir }}/dib-workaround.sh
    |& tee {{ artib_working_dir }}/dib-workaround.sh.log
  environment:
    LIBGUESTFS_BACKEND: direct
  when: artib_dib_workarounds

- name: script to prepare for image building with DIB
  template:
    src: "{{ artib_dib_prepare_script }}"
    dest: "{{ artib_working_dir }}/dib-prepare-script.sh"
    mode: 0744

- name: Run DIB prep script
  shell: >
    {{ artib_working_dir }}/dib-prepare-script.sh |& tee
    {{ artib_working_dir }}/dib-prepare-script.sh.log
  become: true

- name: ensure we can sudo without requiring tty for async tasks
  lineinfile:
    dest: /etc/sudoers
    line: '#Defaults requiretty'
    regexp: '^Defaults\s+requiretty'
    backup: yes
  become: true

# default is templates/dib-manifest-centos7-mitaka.yaml.j2
- name: Create yaml manifest for DIB invocation (tripleo-common)
  template:
    src: "{{ artib_image_yaml_template }}"
    dest: "{{ artib_working_dir }}/dib-manifest.yml"

- name: Build the images
  tripleo_build_images:
    config_files:
      - "{{ artib_working_dir }}/dib-manifest.yml"
    output_directory: "{{ artib_working_dir }}"


