---
# TODO: add artib_ to variable names
- name: Delete prior working directory if present
  file:
    path: "{{ working_dir }}"
    state: absent

- name: Create the working directory
  file:
    path: "{{ working_dir }}"
    state: directory
    mode: 0755

# Get the base image and setup repos
- include: repo_setup.yml

# Install packages for overcloud base image
- include: package_install.yml

# Use overcloud base image to create undercloud base image
- include: convert_undercloud.yml

# default: vars/dib-config-centos7-mitaka.yml
- include_vars: "dib-config-{{ base_os }}-{{ release }}.yml"

# Use DIB to build the images (default: overlcloud-full, IPA)
- include: dib_build.yml

# Inject overcloud-full and IPA images into the undercloud image
- include: undercloud_inject.yml