#
# ansible-role-tripleo-image-build is getting an overhaul.
#
# "legacy" oooq image is an undercloud containing overcloud + IPA injected.
#
# until we have kinks worked out and have landed patches in tripleo-quickstart and here, we're
# keeping it around as a default.  We are moving to an undercloud merely being a time capsule
# containing a local snapshot of the repository metadata and rpm's reposync'd.  quickstart will
# create the images (very quickly) based on preloaded rpm cache / local repo.
#
# for more info:
#   https://trello.com/c/o6g4kqcc/316-oooq-pipeline-improvements-reposync-reporting-on-deps-and-content-handle-network-hiccups-with-grace
#   https://trello.com/c/ElpnAntE/163-dlrn-record-full-repository-state
#   https://github.com/redhat-openstack/ansible-role-tripleo-image-build/issues/32
#

- include: legacy-main.yml
  when: artib_legacy_mode is true

- include: artib-main.yml
  when: artib_legacy_mode is not true
