---
- name: Get the overcloud base image
  get_url:
    url: '{{ overcloud_base_image_url }}'
    dest: '{{ working_dir }}/overcloud-base.qcow2'
    force: '{{ overcloud_overwrite_existing }}'

- include_vars: "{{ overcloud_package_list }}"

- name: Template script to install packages in the overcloud image
  template:
    src: "{{ package_install_script }}"
    dest: "{{ working_dir }}/package-install.sh"

- name: Install the packages in the overcloud image using virt-customize
  shell: >
    virt-customize -m {{ virt_customize_ram }}
    --smp {{ virt_customize_cpu }}
    -a {{ working_dir }}/overcloud-base.qcow2
    --run {{ working_dir }}/package-install.sh
  environment:
    LIBGUESTFS_BACKEND: direct
