- name: install scp
  yum:
    name: openssh-clients
    state: present
  become: true

- name: Copy publishing key to source
  copy: src={{ publish_dest_key }} dest={{ working_dir }}/publish-identity mode=0600
  when: publish_dest_key is defined

- name: create destination directory
  command: >
    ssh
    -o StrictHostKeyChecking=no

    {% if publish_dest_key is defined %}
    -i {{ working_dir }}/publish-identity
    {% endif %}

    {% if publish_dest_user is defined %}
    {{ publish_dest_user }}@{{ publish_dest_host }}
    {% else %}
    {{ publish_dest_host }}
    {% endif %}

    mkdir -p {{ publish_dest_basepath }}
  when: publish_create_dest_via_ssh

- name: Direct publish images and artifacts
  command: >
    scp
    -o StrictHostKeyChecking=no

    {% if publish_dest_key is defined %}
    -i {{ working_dir }}/publish-identity
    {% endif %}

    {{ working_dir }}/{{ item }}

    {% if publish_dest_user is defined %}
    {{ publish_dest_user }}@{{ publish_dest_host }}:{{ publish_dest_basepath }}
    {% else %}
    {{ publish_dest_host }}:{{ publish_dest_basepath }}
    {% endif %}
  with_items: "{{ artifacts }}"

