# artib_publish_artifacts defines list of artifacts to move

# artib_publish: false
# artib_publish_dest_user:           username
# artib_publish_dest_host:           resolvable hostname/ip
# artib_publish_dest_basepath:       host:basepath
# artib_publish_create_dest_via_ssh: false

# optional
# publish_dest_key: "localpath/to/your/identity/file"
- name: install scp
  yum:
    name: openssh-clients
    state: present
  become: true

- name: Copy publishing key to source
  copy: src={{ artib_publish_dest_key }} dest={{ artib_working_dir }}/publish-identity mode=0600
  when: artib_publish_dest_key is defined

- name: create destination directory
  command: >
    ssh
    -o StrictHostKeyChecking=no

    {% if artib_publish_dest_key is defined %}
    -i {{ artib_working_dir }}/publish-identity
    {% endif %}

    {% if artib_publish_dest_user is defined %}
    {{ artib_publish_dest_user }}@{{ artib_publish_dest_host }}
    {% else %}
    {{ artib_publish_dest_host }}
    {% endif %}

    mkdir -p {{ artib_publish_dest_basepath }}
  when: artib_publish_create_dest_via_ssh

- name: Direct publish images and artifacts
  command: >
    scp
    -o StrictHostKeyChecking=no

    {% if artib_publish_dest_key is defined %}
    -i {{ artib_working_dir }}/publish-identity
    {% endif %}

    {{ artib_working_dir }}/{{ item }}

    {% if artib_publish_dest_user is defined %}
    {{ artib_publish_dest_user }}@{{ artib_publish_dest_host }}:{{ artib_publish_dest_basepath }}
    {% else %}
    {{ artib_publish_dest_host }}:{{ artib_publish_dest_basepath }}
    {% endif %}
  with_items: "{{ artib_publish_artifacts }}"

