---
- name: Get the minimal base image
  get_url:
    url: '{{ artib_minimal_base_image_url }}'
    dest: '{{ artib_working_dir }}/minimal-base.qcow2'
    force: '{{ artib_minimal_overwrite_existing }}'

- name: Template script to setup repos in the base image
  template:
    src: "{{ artib_repo_script }}"
    dest: "{{ artib_working_dir }}/repo_setup.sh"

- name: Setup repos in the base image using virt-customize
  shell: virt-customize {{ artib_vc_args }} -a minimal-base.qcow2 --run repo_setup.sh > repo_setup.sh.log 2>&1
  environment:
    LIBGUESTFS_BACKEND: direct
  args:
    chdir: "{{ artib_working_dir }}"
