---
- name: Template script to setup swap in the base image
  template:
    src: "{{ artib_swapfile_script }}"
    dest: "{{ artib_working_dir }}/swapfile-create.sh"

# works on the undercloud-base.qcow2, the overcloud-full.qcow2 image is not currently large enough
- name: Setup repos in the image using virt-customize
  shell: virt-customize {{ artib_vc_args }} -a {{ artib_working_dir }}/{{ item }} --run swapfile-create.sh > swapfile_create_{{ item }}.log 2>&1
  environment:
    LIBGUESTFS_BACKEND: direct
  args:
    chdir: "{{ artib_working_dir }}"
  with_items:
    - undercloud-base.qcow2
