---
- name: Inject overcloud images into undercloud image
  shell: >
    virt-customize -m {{ virt_customize_ram }}
    --smp {{ virt_customize_cpu }}
    -a {{ working_dir }}/undercloud-base.qcow2
    --upload {{ working_dir }}/{{ item }}:/home/stack
  environment:
    LIBGUESTFS_BACKEND: direct
  with_items: "{{ overcloud_images_kilo }}"

- name: Compress undercloud image
  shell: |
    virt-sparsify --tmp {{ working_dir }} --check-tmpdir {{ virt_sparsify_checktmpdir_flag }} \
      --compress undercloud-base.qcow2 undercloud.qcow2
    md5sum undercloud.qcow2 > undercloud.qcow2.md5
  environment:
    LIBGUESTFS_BACKEND: direct
  args:
    chdir: "{{ working_dir }}"

- name: Tar overcloud-full image files
  shell: |
    tar -cf overcloud-full.tar overcloud-full*
    md5sum overcloud-full.tar > overcloud-full.tar.md5
  args:
    chdir: "{{ working_dir }}"

