---
- name: Inject overcloud images into undercloud image
  shell: >
    virt-customize -m {{ virt_customize_ram }}
    --smp {{ virt_customize_cpu }}
    -a {{ working_dir }}/undercloud-base.qcow2
    --upload {{ working_dir }}/{{ item }}:/home/stack
  environment:
    LIBGUESTFS_BACKEND: direct
  with_items: "{{ artib_overcloud_images }}"

# TODO: fix working_dir --> artib_working_dir

- name: Compress undercloud image
  shell: |
    virt-sparsify --tmp {{ working_dir }} --check-tmpdir {{ virt_sparsify_checktmpdir_flag }} \
      --compress undercloud-base.qcow2 undercloud.qcow2
    md5sum undercloud.qcow2 > undercloud.qcow2.md5
  environment:
    LIBGUESTFS_BACKEND: direct
  args:
    chdir: "{{ working_dir }}"

# TODO: the replace filter to remove .qcow2 seems like a cludge.  Determine if filenames are fixed
- name: Create Tars of images
  vars:
    tar_base_fname: {{ item.value.output_image | replace(".qcow2", "") }}
  shell: |
    tar -cf {{ tar_base_fname }}.tar {{ tar_base_fname }}*
    md5sum {{ tar_base_fname }}.tar > {{ tar_base_fname }}.tar.md5
  args:
    chdir: "{{ working_dir }}"
  with_dict: "{{ artib_dib_images }}"

