---
- name: Inject overcloud images into undercloud image
  shell: >
    virt-customize -m {{ artib_virt_customize_ram }}
    --smp {{ artib_virt_customize_cpu }}
    -a {{ artib_working_dir }}/undercloud-base.qcow2
    --upload {{ artib_working_dir }}/{{ item }}:/home/stack
  environment:
    LIBGUESTFS_BACKEND: direct
  with_items: "{{ artib_overcloud_images }}"

- name: Compress undercloud image
  shell: |
    virt-sparsify --tmp {{ artib_working_dir }} --check-tmpdir {{ artib_virt_sparsify_checktmpdir_flag }} \
      --compress undercloud-base.qcow2 undercloud.qcow2
    md5sum undercloud.qcow2 > undercloud.qcow2.md5
  environment:
    LIBGUESTFS_BACKEND: direct
  args:
    chdir: "{{ artib_working_dir }}"

- name: Tar overcloud-full image files
  shell: |
    tar -cf overcloud-full.tar overcloud-full*
    md5sum overcloud-full.tar > overcloud-full.tar.md5
  args:
    chdir: "{{ artib_working_dir }}"

- name: Tar agent ramdisk files
  shell: |
    tar -cf ironic-python-agent.tar ironic-python-agent*
    md5sum ironic-python-agent.tar > ironic-python-agent.tar.md5
  args:
    chdir: "{{ artib_working_dir }}"
