#
# images that will be created using disk-image-create.  openstack binaries are installed
# on these images to produce the final images.
#
# the 'env' dict is appended to the env for the disk-image-create calls, and will
# override values defined in dib_build.yml.
#
# More: http://docs.openstack.org/developer/diskimage-builder/
#
artib_dib_images:

  ###
  image_ipa:
    output_image: ironic-python-agent
    base_image:   minimal-base.qcow2
    elements:
      - centos7
      - dhcp-all-interfaces
      - dynamic-login
      - selinux-permissive
      - pip-and-virtualenv-override
      - ironic-agent
    projects:
      - python-hardware-detect
    env:
      DIB_SHOW_IMAGE_USAGE: 1
    min_tmpfs_size: 5
    logfile: dib-agent-ramdisk.log

  ###
  image_overcloud:
    output_image: overcloud-full.qcow2
    base_image:   overcloud-base.qcow2
    elements:
      - centos7
      - baremetal
      - dhcp-all-interfaces
      - stable-interface-names
      - grub2
      - dynamic-login
      - selinux-permissive
      - element-manifest
      - heat-config-puppet
      - heat-config-script
      - hosts
      - network-gateway
      - os-net-config
      - sysctl
      - hiera
      - pip-and-virtualenv-override
    projects:
    env:
      DIB_SHOW_IMAGE_USAGE: 1
      # Needed for corosync to be able to use hostnames https://bugs.launchpad.net/tripleo/+bug/1447497
      DIB_CLOUD_INIT_ETC_HOSTS: ''
    min_tmpfs_size: 5
    logfile: dib-overcloud-full.log

# undercloud_inject vars
artib_overcloud_images:
  - ironic-python-agent.initramfs
  - ironic-python-agent.kernel
  - overcloud-full.initrd
  - overcloud-full.qcow2
  - overcloud-full.vmlinuz

artib_overcloud_packages:
  - automake
  - boost-filesystem
  - boost-program-options
  - ceph
  - corosync
  - docker-registry
  - fence-agents-all
  - gcc-c++
  - git
  - haproxy
  - httpd
  - iptables-services
  - ipxe-bootimgs
  - iscsi-initiator-utils
  - keepalived
  - kernel-devel
  - libguestfs-tools
  - libvirt
  - libwsman1
  - libxslt-devel
  - mariadb
  - mariadb-devel
  - mariadb-galera-server
  - memcached
  - mongodb
  - mongodb-server
  - ntp
  - openstack-ceilometer-alarm
  - openstack-ceilometer-api
  - openstack-ceilometer-central
  - openstack-ceilometer-collector
  - openstack-ceilometer-compute
  - openstack-ceilometer-notification
  - openstack-ceilometer-polling
  - openstack-cinder
  - openstack-dashboard
  - openstack-glance
  - openstack-gnocchi-api
  - openstack-gnocchi-carbonara
  - openstack-gnocchi-common
  - openstack-gnocchi-indexer-sqlalchemy
  - openstack-gnocchi-metricd
  - openstack-gnocchi-statsd
  - openstack-heat-api
  - openstack-heat-api-cfn
  - openstack-heat-api-cloudwatch
  - openstack-heat-engine
  - openstack-ironic-api
  - openstack-ironic-conductor
  - openstack-ironic-inspector
  - openstack-keystone
  - openstack-manila
  - openstack-manila-share
  - openstack-neutron
  - openstack-neutron-lbaas
  - openstack-neutron-metering-agent
  - openstack-neutron-ml2
  - openstack-neutron-openvswitch
  - openstack-nova-api
  - openstack-nova-cert
  - openstack-nova-compute
  - openstack-nova-conductor
  - openstack-nova-console
  - openstack-nova-novncproxy
  - openstack-nova-scheduler
  - openstack-puppet-modules
  - openstack-sahara
  - openstack-selinux
  - openstack-swift-account
  - openstack-swift-object
  - openstack-swift-proxy
  - openstack-tempest
  - openvswitch
  - openwsman-python
  - os-apply-config
  - os-cloud-config
  - os-collect-config
  - os-refresh-config
  - os-net-config
  - pacemaker
  - pacemaker-remote
  - pcs
  - pystache
  - python-gnocchiclient
  - python-ipaddr
  - python-libguestfs
  - python-openvswitch
  - python-pip
  - python-pbr
  - python-tripleoclient
  - python-troveclient
  - python-virtualenv
  - python-zaqarclient
  - puppet
  - rabbitmq-server
  - redis
  - screen
  - syslinux
  - targetcli
  - tcpdump
  - tftp
  - tftp-server
  - traceroute
  - vim
  - wget
  - xinetd
