- name: get cpu flags
  command: >
    awk -F: '/^flags/ {print $2}' /proc/cpuinfo
  register: cpu_flags_cmd

- name: set cpu flags fact
  set_fact:
    cpu_flags: "{{ cpu_flags_cmd.stdout.split() }}"

- name: check if Intel processor
  command: grep -q Intel /proc/cpuinfo
  ignore_errors: true
  register: is_intel

- name: check if AMD processor
  command: grep -q AMD /proc/cpuinfo
  ignore_errors: true
  register: is_amd

- name: set nested_virt fact
  set_fact:
    nested_virt: >-
      {{ ((is_intel and 'vmx' in cpu_flags)
      or (is_amd and 'svm' in cpu_flags))|bool }}

- name: configure kvm module
  copy:
    dest: /etc/modprobe.d/kvm.conf
    content: |
      options kvm_intel nested=1 {{kvm_intel_options}}
      options kvm_amd nested=1 {{kvm_amd_options}}
  when: "{{ nested_virt }}"
  become: true

- name: load kvm module [intel]
  command: modprobe kvm_intel
  when: is_intel|success
  become: true

- name: load kvm module [amd]
  command: modprobe kvm_amd
  when: is_amd|success
  become: true

- name: arrange for kvm module to load at boot [intel]
  copy:
    content: kvm_intel
    dest: /etc/modules-load.d/ooo_kvm.conf
  when: is_intel|success
  become: true

- name: arrange for kvm module to load at boot [amd]
  copy:
    content: kvm_amd
    dest: /etc/modules-load.d/ooo_kvm.conf
  when: is_amd|success
  become: true


